# vim:syntax=yaml
version: 2
defaults: &defaults 
  docker:
    - image: morxa/fawkes-buildenv:f27-kinetic
jobs:
  build:
    <<: *defaults
    steps:
      - run: dnf install ccache
      - run:
          name: "Add ROS to the bash environment"
          command: |
            echo 'source /usr/lib64/ros/setup.bash' >> $BASH_ENV
      - restore_cache:
          keys:
            - build-v1-{{ .Branch }}-{{ .Revision }}
            - build-v1-{{ .Branch }}-
            - build-v1-master-
            - build-v1-
      - checkout
      - run: make -C src/libs/core
      - save_cache:
          key: build-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - $HOME/.ccache
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  test:
    <<: *defaults
    steps: 
      - attach_workspace:
          at: .
      - run: make test
  check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - check:
          requires:
            - build
