# vim:syntax=yaml
version: 2
defaults: &defaults 
  docker:
    - image: morxa/fawkes-buildenv:f27-kinetic
jobs:
  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - build-v1-{{ .Branch }}-{{ .Revision }}
            - build-v1-{{ .Branch }}
            - build-v1
      - checkout
      - run: make all gui
      - save_cache:
          key: build-v1-{{ .Branch }}-{{ .Revision }}
          path: .
  test:
    <<: *defaults
    steps: 
      - run: make test
  check:
    <<: *defaults
    steps:
      - run: make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - check:
          requires:
            - build
