# vim:syntax=yaml
version: 2
defaults: &defaults 
  docker:
    - image: morxa/fawkes-buildenv:f27-kinetic
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: make all gui
  test:
    <<: *defaults
    steps: 
      - run: make test
  check:
    <<: *defaults
    steps:
      - run: make check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - check:
          requires:
            - build
